### ISSUE TITLE
Murrurundi BushBash Devs Topics

### ISSUE THREAD

**Issue by nickfarrow** [MelbourneBitDevs/bitdevs.com.au#19]
Suggest topics to discuss at the first Bush Bash Devs this Friday at Murrurundi ⚡️💻

During the session we'll go through each topic and figure out as a group what it is about, the technical underpinnings, and implications.

Share any recent topics on this GitHub issue: Bitcoin, news, free software, tech, privacy, or related!

**Comment by nickfarrow** [comment]
Swan Bitcoin to Stop Serving Customers Interacting with Privacy Services
https://www.nobsbitcoin.com/swan-bitcoin-privacy-update/

**Comment by nickfarrow** [comment]
"OP threw a 5"

https://www.reddit.com/r/coldcard/comments/17epqk8/040_bitcoin_taken_instantly_from_my_coldcard/

**Comment by humansinstitute** [comment]
Offers style LN address scheme

https://bitcoinops.org/en/newsletters/2023/11/22/

**Comment by humansinstitute** [comment]
83.7 BTC Fee

https://mempool.space/tx/b5a2af5845a8d3796308ff9840e567b14cf6bb158ff26c999e6f9a1f5448f9aa

**Comment by humansinstitute** [comment]
Binance settlement with Justice Department

https://www.cnbc.com/2023/11/22/whats-next-for-binance-after-doj-settlement-departure-of-changpeng-zhao.html

**Comment by nickfarrow** [comment]
Rumors Wallet of Satoshi is disappearing from some app stores
https://twitter.com/ZeusLN/status/1727810997656674355
