### ISSUE TITLE
Create a logo for our group

### ISSUE THREAD

**Issue by nickfarrow** [MelbourneBitDevs/bitdevs.com.au#6]
Our own logo would be cool instead of whatever `lionsgate.jpg` is

**Comment by humansinstitute** [comment]
I just generated this for Perth Bitdevs on Dalle

![bitcoin-lightnint](https://github.com/MelbourneBitDevs/bitdevs.com.au/assets/42595944/18a30abf-ce69-4faf-8b3a-50d5baeebdbb)

![Aus-Bitdevs](https://github.com/MelbourneBitDevs/bitdevs.com.au/assets/42595944/399a826e-4db3-4e4c-8ce0-ad06f61ba916)

![Aus-Bitdevs-2](https://github.com/MelbourneBitDevs/bitdevs.com.au/assets/42595944/8209d019-e56c-45c2-b5b8-7a4a8ef2d735)

**Comment by nickfarrow** [comment]
Awesome, we might put one of these somewhere.

`@_Bosch_` (i think) made an awesome image to replace the og_image and link preview that we are currently using
https://github.com/MelbourneBitDevs/bitdevs.com.au/blob/master/header.jpg
